/**
 * MappingMapTocatalog2.java
 *
 * This file was generated by MapForce 2021r2sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */
package com.mapforce;
import com.altova.mapforce.*;
import com.altova.types.*;
import com.altova.xml.*;
import com.altova.text.tablelike.*;
import com.altova.text.*;
import com.altova.text.edi.*;
import java.util.*;

public class MappingMapTocatalog2 extends com.altova.TraceProvider {
	private boolean runDoesCloseAll = true;
	public void setCloseObjectsAfterRun(boolean c) {runDoesCloseAll = c;}
	public boolean getCloseObjectsAfterRun() {return runDoesCloseAll;}


	static class main implements IEnumerable {
		com.altova.mapforce.IMFNode var1_product_alone_Instance;

		public main(com.altova.mapforce.IMFNode var1_product_alone_Instance)	{
			this.var1_product_alone_Instance = var1_product_alone_Instance;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}

		public static class Enumerator implements IEnumerator {
			int pos = 0;
			int state = 2;
			Object current;
			main closure;

			public Enumerator(main closure) {
				this.closure = closure;
			}

			public Object current() {return current;}

			public int position() {return pos;}

			public boolean moveNext() throws Exception {
				while (state != 0) {
					switch (state) {
						case 2: if (moveNext_2()) return true; break;
					}
				}
				return false;
			}

			private boolean moveNext_2() throws Exception {
				state = 0;				
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("catalog", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), (new seq1_join(closure.var1_product_alone_Instance)));
				pos++;
				return true;
			}


			public void close() {
			}
		}
	}
	static class seq1_join implements IEnumerable {
		com.altova.mapforce.IMFNode var1_product_alone_Instance;

		public seq1_join(com.altova.mapforce.IMFNode var1_product_alone_Instance)	{
			this.var1_product_alone_Instance = var1_product_alone_Instance;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}

		public static class Enumerator implements IEnumerator {
			int pos = 0;
			int state = 1;
			Object current;
			seq1_join closure;
			IEnumerator var2_filter;
			IEnumerator var3_object_member_by_name;
			IEnumerator var4_as_array;
			IEnumerator var5_join;
			IEnumerator var6_object_member_by_name;
			IEnumerator var7_as_string;
			com.altova.mapforce.IEnumerable var8_box;
			com.altova.mapforce.IEnumerable var9_object_member_by_name;
			com.altova.mapforce.IEnumerable var10_object_member_by_name;
			IEnumerator var11_object_member_by_name;
			IEnumerator var12_as_string;
			IEnumerator var14_object_member_by_name;
			com.altova.mapforce.IEnumerable var13_box;
			IEnumerator var15_as_string;
			com.altova.mapforce.IEnumerable var16_box;

			public Enumerator(seq1_join closure) {
				this.closure = closure;
			}

			public Object current() {return current;}

			public int position() {return pos;}

			public boolean moveNext() throws Exception {
				while (state != 0) {
					switch (state) {
						case 1: if (moveNext_1()) return true; break;
						case 2: if (moveNext_2()) return true; break;
						case 3: if (moveNext_3()) return true; break;
						case 4: if (moveNext_4()) return true; break;
						case 5: if (moveNext_5()) return true; break;
						case 6: if (moveNext_6()) return true; break;
						case 7: if (moveNext_7()) return true; break;
						case 8: if (moveNext_8()) return true; break;
						case 9: if (moveNext_9()) return true; break;
						case 10: if (moveNext_10()) return true; break;
						case 11: if (moveNext_11()) return true; break;
						case 12: if (moveNext_12()) return true; break;
						case 13: if (moveNext_13()) return true; break;
						case 14: if (moveNext_14()) return true; break;
						case 15: if (moveNext_15()) return true; break;
						case 16: if (moveNext_16()) return true; break;
						case 17: if (moveNext_17()) return true; break;
						case 18: if (moveNext_18()) return true; break;
						case 19: if (moveNext_19()) return true; break;
						case 21: if (moveNext_21()) return true; break;
						case 22: if (moveNext_22()) return true; break;
						case 23: if (moveNext_23()) return true; break;
						case 24: if (moveNext_24()) return true; break;
					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				current = com.altova.functions.Core.createAttribute(com.altova.functions.Core.createQName("xsi:schemaLocation", "http://www.w3.org/2001/XMLSchema-instance"), com.altova.functions.Core.box("http://www.demandware.com/xml/impex/catalog/2006-10-31 file:///C:/Users/admin/Desktop/output%20files/catalog.xsd"));
				pos++;
				return true;
			}
			private boolean moveNext_2() throws Exception {
				state = 3;				
				var2_filter = ((new seq2_join(closure.var1_product_alone_Instance))).enumerator();
				return false;
			}
			private boolean moveNext_3() throws Exception {
				state = 5;				
				if (!var2_filter.moveNext()) {state = 4; return false; }
				if (!(com.altova.functions.Json.IsA(((com.altova.mapforce.IMFNode)(var2_filter.current())), "file:///C:/Users/admin/Desktop/output%20files/product-alone.schema.json#//definitions//object_04/@64"))) {state = 3; return false; }
				var3_object_member_by_name = (com.altova.functions.Json.GetMemberByName(((com.altova.mapforce.IMFNode)(var2_filter.current())), "products")).enumerator();
				return false;
			}
			private boolean moveNext_4() throws Exception {
				state = 0;				
				if( var2_filter != null ) { var2_filter.close(); var2_filter = null; }
				return false;
			}
			private boolean moveNext_5() throws Exception {
				state = 7;				
				if (!var3_object_member_by_name.moveNext()) {state = 6; return false; }
				var4_as_array = (com.altova.functions.Json.AsArray(com.altova.functions.Json.GetMemberValue(((com.altova.mapforce.IMFNode)(var3_object_member_by_name.current()))))).enumerator();
				return false;
			}
			private boolean moveNext_6() throws Exception {
				state = 3;				
				if( var3_object_member_by_name != null ) { var3_object_member_by_name.close(); var3_object_member_by_name = null; }
				return false;
			}
			private boolean moveNext_7() throws Exception {
				state = 9;				
				if (!var4_as_array.moveNext()) {state = 8; return false; }
				var5_join = ((new seq3_join(((com.altova.mapforce.IMFNode)(var4_as_array.current()))))).enumerator();
				return false;
			}
			private boolean moveNext_8() throws Exception {
				state = 5;				
				if( var4_as_array != null ) { var4_as_array.close(); var4_as_array = null; }
				return false;
			}
			private boolean moveNext_9() throws Exception {
				state = 11;				
				if (!var5_join.moveNext()) {state = 10; return false; }
				var6_object_member_by_name = (com.altova.functions.Json.GetMemberByName(((com.altova.mapforce.IMFNode)(var5_join.current())), "Acme Tools Salesforce Sub-Category 2")).enumerator();
				return false;
			}
			private boolean moveNext_10() throws Exception {
				state = 7;				
				if( var5_join != null ) { var5_join.close(); var5_join = null; }
				return false;
			}
			private boolean moveNext_11() throws Exception {
				state = 13;				
				if (!var6_object_member_by_name.moveNext()) {state = 12; return false; }
				var7_as_string = (com.altova.functions.Json.AsString(com.altova.functions.Json.GetMemberValue(((com.altova.mapforce.IMFNode)(var6_object_member_by_name.current()))))).enumerator();
				return false;
			}
			private boolean moveNext_12() throws Exception {
				state = 9;				
				if( var6_object_member_by_name != null ) { var6_object_member_by_name.close(); var6_object_member_by_name = null; }
				return false;
			}
			private boolean moveNext_13() throws Exception {
				state = 15;				
				if (!var7_as_string.moveNext()) {state = 14; return false; }
				var8_box = new com.altova.functions.Core.SequenceCache(com.altova.functions.Core.box(((java.lang.String)(var7_as_string.current()))));
				var9_object_member_by_name = new com.altova.functions.Core.SequenceCache(com.altova.functions.Json.GetMemberByName(((com.altova.mapforce.IMFNode)(var5_join.current())), "Acme Tools Salesforce Sub-Category 1"));
				var10_object_member_by_name = new com.altova.functions.Core.SequenceCache(com.altova.functions.Json.GetMemberByName(((com.altova.mapforce.IMFNode)(var5_join.current())), "Acme Tools Salesforce Category"));
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("category", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), (new seq4_join(var9_object_member_by_name, var8_box)));
				pos++;
				return true;
			}
			private boolean moveNext_14() throws Exception {
				state = 11;				
				if( var7_as_string != null ) { var7_as_string.close(); var7_as_string = null; }
				return false;
			}
			private boolean moveNext_15() throws Exception {
				state = 16;				
				var11_object_member_by_name = (var9_object_member_by_name).enumerator();
				return false;
			}
			private boolean moveNext_16() throws Exception {
				state = 18;				
				if (!var11_object_member_by_name.moveNext()) {state = 17; return false; }
				var12_as_string = (com.altova.functions.Json.AsString(com.altova.functions.Json.GetMemberValue(((com.altova.mapforce.IMFNode)(var11_object_member_by_name.current()))))).enumerator();
				return false;
			}
			private boolean moveNext_17() throws Exception {
				state = 21;				
				if( var11_object_member_by_name != null ) { var11_object_member_by_name.close(); var11_object_member_by_name = null; }
				var14_object_member_by_name = (var10_object_member_by_name).enumerator();
				return false;
			}
			private boolean moveNext_18() throws Exception {
				state = 18;				
				if (!var12_as_string.moveNext()) {state = 19; return false; }
				var13_box = new com.altova.functions.Core.SequenceCache(com.altova.functions.Core.box(((java.lang.String)(var12_as_string.current()))));
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("category", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), (new seq5_join(var10_object_member_by_name, var13_box)));
				pos++;
				return true;
			}
			private boolean moveNext_19() throws Exception {
				state = 16;				
				if( var12_as_string != null ) { var12_as_string.close(); var12_as_string = null; }
				return false;
			}
			private boolean moveNext_21() throws Exception {
				state = 23;				
				if (!var14_object_member_by_name.moveNext()) {state = 22; return false; }
				var15_as_string = (com.altova.functions.Json.AsString(com.altova.functions.Json.GetMemberValue(((com.altova.mapforce.IMFNode)(var14_object_member_by_name.current()))))).enumerator();
				return false;
			}
			private boolean moveNext_22() throws Exception {
				state = 13;				
				if( var14_object_member_by_name != null ) { var14_object_member_by_name.close(); var14_object_member_by_name = null; }
				return false;
			}
			private boolean moveNext_23() throws Exception {
				state = 23;				
				if (!var15_as_string.moveNext()) {state = 24; return false; }
				var16_box = new com.altova.functions.Core.SequenceCache(com.altova.functions.Core.box(((java.lang.String)(var15_as_string.current()))));
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("category", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), (new seq6_seq_(var16_box)));
				pos++;
				return true;
			}
			private boolean moveNext_24() throws Exception {
				state = 21;				
				if( var15_as_string != null ) { var15_as_string.close(); var15_as_string = null; }
				return false;
			}


			public void close() {
				try {
					if( var12_as_string != null ) { var12_as_string.close(); var12_as_string = null; }
					if( var11_object_member_by_name != null ) { var11_object_member_by_name.close(); var11_object_member_by_name = null; }
					if( var15_as_string != null ) { var15_as_string.close(); var15_as_string = null; }
					if( var14_object_member_by_name != null ) { var14_object_member_by_name.close(); var14_object_member_by_name = null; }
					if( var7_as_string != null ) { var7_as_string.close(); var7_as_string = null; }
					if( var6_object_member_by_name != null ) { var6_object_member_by_name.close(); var6_object_member_by_name = null; }
					if( var5_join != null ) { var5_join.close(); var5_join = null; }
					if( var4_as_array != null ) { var4_as_array.close(); var4_as_array = null; }
					if( var3_object_member_by_name != null ) { var3_object_member_by_name.close(); var3_object_member_by_name = null; }
					if( var2_filter != null ) { var2_filter.close(); var2_filter = null; }
				} catch (Exception e) {
				}
			}
		}
	}
	static class seq2_join implements IEnumerable {
		com.altova.mapforce.IMFNode var1_product_alone_Instance;

		public seq2_join(com.altova.mapforce.IMFNode var1_product_alone_Instance)	{
			this.var1_product_alone_Instance = var1_product_alone_Instance;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}

		public static class Enumerator implements IEnumerator {
			int pos = 0;
			int state = 1;
			Object current;
			seq2_join closure;
			IEnumerator var2_as_array;
			IEnumerator var3_array_items;
			IEnumerator var4_as_object;

			public Enumerator(seq2_join closure) {
				this.closure = closure;
			}

			public Object current() {return current;}

			public int position() {return pos;}

			public boolean moveNext() throws Exception {
				while (state != 0) {
					switch (state) {
						case 1: if (moveNext_1()) return true; break;
						case 2: if (moveNext_2()) return true; break;
						case 3: if (moveNext_3()) return true; break;
						case 4: if (moveNext_4()) return true; break;
						case 5: if (moveNext_5()) return true; break;
						case 6: if (moveNext_6()) return true; break;
						case 7: if (moveNext_7()) return true; break;
					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				var2_as_array = (com.altova.functions.Json.AsArray(com.altova.functions.Json.RootValue(closure.var1_product_alone_Instance))).enumerator();
				return false;
			}
			private boolean moveNext_2() throws Exception {
				state = 4;				
				if (!var2_as_array.moveNext()) {state = 3; return false; }
				var3_array_items = (com.altova.functions.Json.GetArrayItems(((com.altova.mapforce.IMFNode)(var2_as_array.current())))).enumerator();
				return false;
			}
			private boolean moveNext_3() throws Exception {
				state = 0;				
				if( var2_as_array != null ) { var2_as_array.close(); var2_as_array = null; }
				return false;
			}
			private boolean moveNext_4() throws Exception {
				state = 6;				
				if (!var3_array_items.moveNext()) {state = 5; return false; }
				var4_as_object = (com.altova.functions.Json.AsObject(((com.altova.mapforce.IMFNode)(var3_array_items.current())))).enumerator();
				return false;
			}
			private boolean moveNext_5() throws Exception {
				state = 2;				
				if( var3_array_items != null ) { var3_array_items.close(); var3_array_items = null; }
				return false;
			}
			private boolean moveNext_6() throws Exception {
				state = 6;				
				if (!var4_as_object.moveNext()) {state = 7; return false; }
				current = var4_as_object.current();
				pos++;
				return true;
			}
			private boolean moveNext_7() throws Exception {
				state = 4;				
				if( var4_as_object != null ) { var4_as_object.close(); var4_as_object = null; }
				return false;
			}


			public void close() {
				try {
					if( var4_as_object != null ) { var4_as_object.close(); var4_as_object = null; }
					if( var3_array_items != null ) { var3_array_items.close(); var3_array_items = null; }
					if( var2_as_array != null ) { var2_as_array.close(); var2_as_array = null; }
				} catch (Exception e) {
				}
			}
		}
	}
	static class seq3_join implements IEnumerable {
		com.altova.mapforce.IMFNode var1_cur;

		public seq3_join(com.altova.mapforce.IMFNode var1_cur)	{
			this.var1_cur = var1_cur;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}

		public static class Enumerator implements IEnumerator {
			int pos = 0;
			int state = 1;
			Object current;
			seq3_join closure;
			IEnumerator var2_array_items;
			IEnumerator var3_as_object;

			public Enumerator(seq3_join closure) {
				this.closure = closure;
			}

			public Object current() {return current;}

			public int position() {return pos;}

			public boolean moveNext() throws Exception {
				while (state != 0) {
					switch (state) {
						case 1: if (moveNext_1()) return true; break;
						case 2: if (moveNext_2()) return true; break;
						case 3: if (moveNext_3()) return true; break;
						case 4: if (moveNext_4()) return true; break;
						case 5: if (moveNext_5()) return true; break;
					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				var2_array_items = (com.altova.functions.Json.GetArrayItems(closure.var1_cur)).enumerator();
				return false;
			}
			private boolean moveNext_2() throws Exception {
				state = 4;				
				if (!var2_array_items.moveNext()) {state = 3; return false; }
				var3_as_object = (com.altova.functions.Json.AsObject(((com.altova.mapforce.IMFNode)(var2_array_items.current())))).enumerator();
				return false;
			}
			private boolean moveNext_3() throws Exception {
				state = 0;				
				if( var2_array_items != null ) { var2_array_items.close(); var2_array_items = null; }
				return false;
			}
			private boolean moveNext_4() throws Exception {
				state = 4;				
				if (!var3_as_object.moveNext()) {state = 5; return false; }
				current = var3_as_object.current();
				pos++;
				return true;
			}
			private boolean moveNext_5() throws Exception {
				state = 2;				
				if( var3_as_object != null ) { var3_as_object.close(); var3_as_object = null; }
				return false;
			}


			public void close() {
				try {
					if( var3_as_object != null ) { var3_as_object.close(); var3_as_object = null; }
					if( var2_array_items != null ) { var2_array_items.close(); var2_array_items = null; }
				} catch (Exception e) {
				}
			}
		}
	}
	static class seq4_join implements IEnumerable {
		com.altova.mapforce.IEnumerable var1_object_member_by_name;
		com.altova.mapforce.IEnumerable var2_box;

		public seq4_join(com.altova.mapforce.IEnumerable var1_object_member_by_name, com.altova.mapforce.IEnumerable var2_box)	{
			this.var1_object_member_by_name = var1_object_member_by_name;
			this.var2_box = var2_box;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}

		public static class Enumerator implements IEnumerator {
			int pos = 0;
			int state = 1;
			Object current;
			seq4_join closure;
			IEnumerator var3_object_member_by_name;
			IEnumerator var4_as_string;

			public Enumerator(seq4_join closure) {
				this.closure = closure;
			}

			public Object current() {return current;}

			public int position() {return pos;}

			public boolean moveNext() throws Exception {
				while (state != 0) {
					switch (state) {
						case 1: if (moveNext_1()) return true; break;
						case 2: if (moveNext_2()) return true; break;
						case 3: if (moveNext_3()) return true; break;
						case 4: if (moveNext_4()) return true; break;
						case 5: if (moveNext_5()) return true; break;
						case 6: if (moveNext_6()) return true; break;
						case 7: if (moveNext_7()) return true; break;
					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("display-name", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), closure.var2_box);
				pos++;
				return true;
			}
			private boolean moveNext_2() throws Exception {
				state = 3;				
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("description", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), closure.var2_box);
				pos++;
				return true;
			}
			private boolean moveNext_3() throws Exception {
				state = 4;				
				var3_object_member_by_name = (closure.var1_object_member_by_name).enumerator();
				return false;
			}
			private boolean moveNext_4() throws Exception {
				state = 6;				
				if (!var3_object_member_by_name.moveNext()) {state = 5; return false; }
				var4_as_string = (com.altova.functions.Json.AsString(com.altova.functions.Json.GetMemberValue(((com.altova.mapforce.IMFNode)(var3_object_member_by_name.current()))))).enumerator();
				return false;
			}
			private boolean moveNext_5() throws Exception {
				state = 0;				
				if( var3_object_member_by_name != null ) { var3_object_member_by_name.close(); var3_object_member_by_name = null; }
				return false;
			}
			private boolean moveNext_6() throws Exception {
				state = 6;				
				if (!var4_as_string.moveNext()) {state = 7; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("parent", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), com.altova.functions.Core.box(((java.lang.String)(var4_as_string.current()))));
				pos++;
				return true;
			}
			private boolean moveNext_7() throws Exception {
				state = 4;				
				if( var4_as_string != null ) { var4_as_string.close(); var4_as_string = null; }
				return false;
			}


			public void close() {
				try {
					if( var4_as_string != null ) { var4_as_string.close(); var4_as_string = null; }
					if( var3_object_member_by_name != null ) { var3_object_member_by_name.close(); var3_object_member_by_name = null; }
				} catch (Exception e) {
				}
			}
		}
	}
	static class seq5_join implements IEnumerable {
		com.altova.mapforce.IEnumerable var1_object_member_by_name;
		com.altova.mapforce.IEnumerable var2_box;

		public seq5_join(com.altova.mapforce.IEnumerable var1_object_member_by_name, com.altova.mapforce.IEnumerable var2_box)	{
			this.var1_object_member_by_name = var1_object_member_by_name;
			this.var2_box = var2_box;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}

		public static class Enumerator implements IEnumerator {
			int pos = 0;
			int state = 1;
			Object current;
			seq5_join closure;
			IEnumerator var3_object_member_by_name;
			IEnumerator var4_as_string;

			public Enumerator(seq5_join closure) {
				this.closure = closure;
			}

			public Object current() {return current;}

			public int position() {return pos;}

			public boolean moveNext() throws Exception {
				while (state != 0) {
					switch (state) {
						case 1: if (moveNext_1()) return true; break;
						case 2: if (moveNext_2()) return true; break;
						case 3: if (moveNext_3()) return true; break;
						case 4: if (moveNext_4()) return true; break;
						case 5: if (moveNext_5()) return true; break;
						case 6: if (moveNext_6()) return true; break;
						case 7: if (moveNext_7()) return true; break;
					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("display-name", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), closure.var2_box);
				pos++;
				return true;
			}
			private boolean moveNext_2() throws Exception {
				state = 3;				
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("description", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), closure.var2_box);
				pos++;
				return true;
			}
			private boolean moveNext_3() throws Exception {
				state = 4;				
				var3_object_member_by_name = (closure.var1_object_member_by_name).enumerator();
				return false;
			}
			private boolean moveNext_4() throws Exception {
				state = 6;				
				if (!var3_object_member_by_name.moveNext()) {state = 5; return false; }
				var4_as_string = (com.altova.functions.Json.AsString(com.altova.functions.Json.GetMemberValue(((com.altova.mapforce.IMFNode)(var3_object_member_by_name.current()))))).enumerator();
				return false;
			}
			private boolean moveNext_5() throws Exception {
				state = 0;				
				if( var3_object_member_by_name != null ) { var3_object_member_by_name.close(); var3_object_member_by_name = null; }
				return false;
			}
			private boolean moveNext_6() throws Exception {
				state = 6;				
				if (!var4_as_string.moveNext()) {state = 7; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("parent", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), com.altova.functions.Core.box(((java.lang.String)(var4_as_string.current()))));
				pos++;
				return true;
			}
			private boolean moveNext_7() throws Exception {
				state = 4;				
				if( var4_as_string != null ) { var4_as_string.close(); var4_as_string = null; }
				return false;
			}


			public void close() {
				try {
					if( var4_as_string != null ) { var4_as_string.close(); var4_as_string = null; }
					if( var3_object_member_by_name != null ) { var3_object_member_by_name.close(); var3_object_member_by_name = null; }
				} catch (Exception e) {
				}
			}
		}
	}
	static class seq6_seq_ implements IEnumerable {
		com.altova.mapforce.IEnumerable var1_box;

		public seq6_seq_(com.altova.mapforce.IEnumerable var1_box)	{
			this.var1_box = var1_box;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}

		public static class Enumerator implements IEnumerator {
			int pos = 0;
			int state = 1;
			Object current;
			seq6_seq_ closure;

			public Enumerator(seq6_seq_ closure) {
				this.closure = closure;
			}

			public Object current() {return current;}

			public int position() {return pos;}

			public boolean moveNext() throws Exception {
				while (state != 0) {
					switch (state) {
						case 1: if (moveNext_1()) return true; break;
						case 2: if (moveNext_2()) return true; break;
						case 3: if (moveNext_3()) return true; break;
					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("display-name", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), closure.var1_box);
				pos++;
				return true;
			}
			private boolean moveNext_2() throws Exception {
				state = 3;				
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("description", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), closure.var1_box);
				pos++;
				return true;
			}
			private boolean moveNext_3() throws Exception {
				state = 0;				
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("parent", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), com.altova.functions.Core.box("categories"));
				pos++;
				return true;
			}


			public void close() {
			}
		}
	}
	static class Outer implements IEnumerable {
		com.altova.mapforce.IMFNode var1_product_alone_Instance;

		public Outer(com.altova.mapforce.IMFNode var1_product_alone_Instance)	{
			this.var1_product_alone_Instance = var1_product_alone_Instance;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}

		public static class Enumerator implements IEnumerator {
			int pos = 0;
			int state = 1;
			Object current;
			Outer closure;
			IEnumerator var2_box;

			public Enumerator(Outer closure) {
				this.closure = closure;
			}

			public Object current() {return current;}

			public int position() {return pos;}

			public boolean moveNext() throws Exception {
				while (state != 0) {
					switch (state) {
						case 1: if (moveNext_1()) return true; break;
						case 2: if (moveNext_2()) return true; break;
						case 3: if (moveNext_3()) return true; break;
					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				var2_box = ((new main(closure.var1_product_alone_Instance))).enumerator();
				return false;
			}
			private boolean moveNext_2() throws Exception {
				state = 2;				
				if (!var2_box.moveNext()) {state = 3; return false; }
				current = var2_box.current();
				pos++;
				return true;
			}
			private boolean moveNext_3() throws Exception {
				state = 0;				
				if( var2_box != null ) { var2_box.close(); var2_box = null; }
				return false;
			}


			public void close() {
				try {
					if( var2_box != null ) { var2_box.close(); var2_box = null; }
				} catch (Exception e) {
				}
			}
		}
	}


	// instances
	protected com.altova.json.Document varproduct_alone2Instance;

	public void run(String product_alone2SourceFilename, String catalog3TargetFilename) throws Exception {
		try(
			// open source streams
			com.altova.io.FileInput product_alone2Source = new com.altova.io.FileInput(product_alone2SourceFilename);
		// open target stream
			com.altova.io.FileOutput catalog3Target = new com.altova.io.FileOutput(catalog3TargetFilename);

		) {
			// run
			run(product_alone2Source, catalog3Target);

		}
	}


	// main entry point

	public void run(com.altova.io.Input product_alone2Source, com.altova.io.Output catalog3Target) throws Exception {
		// Open the source(s)
			varproduct_alone2Instance = com.altova.functions.Json.Load(product_alone2Source, MapForceJsonLibs_product_alone.Schemas, false, false);

		// Create the target
		org.w3c.dom.Document catalog3Doc = (catalog3Target.getType() == com.altova.io.Output.IO_DOM) ? catalog3Target.getDocument() : XmlTreeOperations.createDocument();

		// Execute mapping

		main mapping = new main(varproduct_alone2Instance);

		com.altova.xml.MFDOMWriter.write(mapping, catalog3Doc);
		// Close the target
		XmlTreeOperations.saveDocument(catalog3Doc, catalog3Target, "UTF-8", false, false, true, false);


		if (runDoesCloseAll) {
			catalog3Target.close();
		}
	}



}
