/**
 * MappingMapTocatalog4.java
 *
 * This file was generated by MapForce 2021r2sp1.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */
package com.mapforce;
import com.altova.mapforce.*;
import com.altova.types.*;
import com.altova.xml.*;
import com.altova.text.tablelike.*;
import com.altova.text.*;
import com.altova.text.edi.*;
import java.util.*;

public class MappingMapTocatalog4 extends com.altova.TraceProvider {
	private boolean runDoesCloseAll = true;
	public void setCloseObjectsAfterRun(boolean c) {runDoesCloseAll = c;}
	public boolean getCloseObjectsAfterRun() {return runDoesCloseAll;}


	static class main implements IEnumerable {
		com.altova.mapforce.IMFNode var1_acmejson_2_Instance;

		public main(com.altova.mapforce.IMFNode var1_acmejson_2_Instance)	{
			this.var1_acmejson_2_Instance = var1_acmejson_2_Instance;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}

		public static class Enumerator implements IEnumerator {
			int pos = 0;
			int state = 2;
			Object current;
			main closure;

			public Enumerator(main closure) {
				this.closure = closure;
			}

			public Object current() {return current;}

			public int position() {return pos;}

			public boolean moveNext() throws Exception {
				while (state != 0) {
					switch (state) {
						case 2: if (moveNext_2()) return true; break;
					}
				}
				return false;
			}

			private boolean moveNext_2() throws Exception {
				state = 0;				
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("catalog", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), (new seq1_join(closure.var1_acmejson_2_Instance)));
				pos++;
				return true;
			}


			public void close() {
			}
		}
	}
	static class seq1_join implements IEnumerable {
		com.altova.mapforce.IMFNode var1_acmejson_2_Instance;

		public seq1_join(com.altova.mapforce.IMFNode var1_acmejson_2_Instance)	{
			this.var1_acmejson_2_Instance = var1_acmejson_2_Instance;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}

		public static class Enumerator implements IEnumerator {
			int pos = 0;
			int state = 1;
			Object current;
			seq1_join closure;
			IEnumerator var2_filter;
			IEnumerator var3_object_member_by_name;
			IEnumerator var4_as_array;
			IEnumerator var5_array_items;
			IEnumerator var6_as_object;
			com.altova.mapforce.IEnumerable var7_object_member_by_name;
			com.altova.mapforce.IEnumerable var8_filter;

			public Enumerator(seq1_join closure) {
				this.closure = closure;
			}

			public Object current() {return current;}

			public int position() {return pos;}

			public boolean moveNext() throws Exception {
				while (state != 0) {
					switch (state) {
						case 1: if (moveNext_1()) return true; break;
						case 2: if (moveNext_2()) return true; break;
						case 3: if (moveNext_3()) return true; break;
						case 4: if (moveNext_4()) return true; break;
						case 5: if (moveNext_5()) return true; break;
						case 6: if (moveNext_6()) return true; break;
						case 7: if (moveNext_7()) return true; break;
						case 8: if (moveNext_8()) return true; break;
						case 9: if (moveNext_9()) return true; break;
						case 10: if (moveNext_10()) return true; break;
						case 11: if (moveNext_11()) return true; break;
						case 12: if (moveNext_12()) return true; break;
					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				current = com.altova.functions.Core.createAttribute(com.altova.functions.Core.createQName("xsi:schemaLocation", "http://www.w3.org/2001/XMLSchema-instance"), com.altova.functions.Core.box("http://www.demandware.com/xml/impex/catalog/2006-10-31 file:///C:/Users/admin/Desktop/output%20files/catalog.xsd"));
				pos++;
				return true;
			}
			private boolean moveNext_2() throws Exception {
				state = 3;				
				var2_filter = ((new seq2_join(closure.var1_acmejson_2_Instance))).enumerator();
				return false;
			}
			private boolean moveNext_3() throws Exception {
				state = 5;				
				if (!var2_filter.moveNext()) {state = 4; return false; }
				if (!(com.altova.functions.Json.IsA(((com.altova.mapforce.IMFNode)(var2_filter.current())), "file:///C:/Users/admin/Desktop/output%20files/acmejson_2.schema.json#//definitions//products_obj/@64"))) {state = 3; return false; }
				var3_object_member_by_name = (com.altova.functions.Json.GetMemberByName(((com.altova.mapforce.IMFNode)(var2_filter.current())), "products")).enumerator();
				return false;
			}
			private boolean moveNext_4() throws Exception {
				state = 0;				
				if( var2_filter != null ) { var2_filter.close(); var2_filter = null; }
				return false;
			}
			private boolean moveNext_5() throws Exception {
				state = 7;				
				if (!var3_object_member_by_name.moveNext()) {state = 6; return false; }
				var4_as_array = (com.altova.functions.Json.AsArray(com.altova.functions.Json.GetMemberValue(((com.altova.mapforce.IMFNode)(var3_object_member_by_name.current()))))).enumerator();
				return false;
			}
			private boolean moveNext_6() throws Exception {
				state = 3;				
				if( var3_object_member_by_name != null ) { var3_object_member_by_name.close(); var3_object_member_by_name = null; }
				return false;
			}
			private boolean moveNext_7() throws Exception {
				state = 9;				
				if (!var4_as_array.moveNext()) {state = 8; return false; }
				var5_array_items = (com.altova.functions.Json.GetArrayItems(((com.altova.mapforce.IMFNode)(var4_as_array.current())))).enumerator();
				return false;
			}
			private boolean moveNext_8() throws Exception {
				state = 5;				
				if( var4_as_array != null ) { var4_as_array.close(); var4_as_array = null; }
				return false;
			}
			private boolean moveNext_9() throws Exception {
				state = 11;				
				if (!var5_array_items.moveNext()) {state = 10; return false; }
				var6_as_object = (com.altova.functions.Json.AsObject(((com.altova.mapforce.IMFNode)(var5_array_items.current())))).enumerator();
				return false;
			}
			private boolean moveNext_10() throws Exception {
				state = 7;				
				if( var5_array_items != null ) { var5_array_items.close(); var5_array_items = null; }
				return false;
			}
			private boolean moveNext_11() throws Exception {
				state = 11;				
				if (!var6_as_object.moveNext()) {state = 12; return false; }
				var7_object_member_by_name = new com.altova.functions.Core.SequenceCache(com.altova.functions.Json.GetMemberByName(((com.altova.mapforce.IMFNode)(var6_as_object.current())), "Main Product Image"));
				var8_filter = new com.altova.functions.Core.SequenceCache((new seq3_filter(((com.altova.mapforce.IMFNode)(var6_as_object.current())))));
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("product", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), (new seq4_join(var7_object_member_by_name, ((com.altova.mapforce.IMFNode)(var6_as_object.current())), var8_filter)));
				pos++;
				return true;
			}
			private boolean moveNext_12() throws Exception {
				state = 9;				
				if( var6_as_object != null ) { var6_as_object.close(); var6_as_object = null; }
				return false;
			}


			public void close() {
				try {
					if( var6_as_object != null ) { var6_as_object.close(); var6_as_object = null; }
					if( var5_array_items != null ) { var5_array_items.close(); var5_array_items = null; }
					if( var4_as_array != null ) { var4_as_array.close(); var4_as_array = null; }
					if( var3_object_member_by_name != null ) { var3_object_member_by_name.close(); var3_object_member_by_name = null; }
					if( var2_filter != null ) { var2_filter.close(); var2_filter = null; }
				} catch (Exception e) {
				}
			}
		}
	}
	static class seq2_join implements IEnumerable {
		com.altova.mapforce.IMFNode var1_acmejson_2_Instance;

		public seq2_join(com.altova.mapforce.IMFNode var1_acmejson_2_Instance)	{
			this.var1_acmejson_2_Instance = var1_acmejson_2_Instance;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}

		public static class Enumerator implements IEnumerator {
			int pos = 0;
			int state = 1;
			Object current;
			seq2_join closure;
			IEnumerator var2_as_array;
			IEnumerator var3_array_items;
			IEnumerator var4_as_object;

			public Enumerator(seq2_join closure) {
				this.closure = closure;
			}

			public Object current() {return current;}

			public int position() {return pos;}

			public boolean moveNext() throws Exception {
				while (state != 0) {
					switch (state) {
						case 1: if (moveNext_1()) return true; break;
						case 2: if (moveNext_2()) return true; break;
						case 3: if (moveNext_3()) return true; break;
						case 4: if (moveNext_4()) return true; break;
						case 5: if (moveNext_5()) return true; break;
						case 6: if (moveNext_6()) return true; break;
						case 7: if (moveNext_7()) return true; break;
					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				var2_as_array = (com.altova.functions.Json.AsArray(com.altova.functions.Json.RootValue(closure.var1_acmejson_2_Instance))).enumerator();
				return false;
			}
			private boolean moveNext_2() throws Exception {
				state = 4;				
				if (!var2_as_array.moveNext()) {state = 3; return false; }
				var3_array_items = (com.altova.functions.Json.GetArrayItems(((com.altova.mapforce.IMFNode)(var2_as_array.current())))).enumerator();
				return false;
			}
			private boolean moveNext_3() throws Exception {
				state = 0;				
				if( var2_as_array != null ) { var2_as_array.close(); var2_as_array = null; }
				return false;
			}
			private boolean moveNext_4() throws Exception {
				state = 6;				
				if (!var3_array_items.moveNext()) {state = 5; return false; }
				var4_as_object = (com.altova.functions.Json.AsObject(((com.altova.mapforce.IMFNode)(var3_array_items.current())))).enumerator();
				return false;
			}
			private boolean moveNext_5() throws Exception {
				state = 2;				
				if( var3_array_items != null ) { var3_array_items.close(); var3_array_items = null; }
				return false;
			}
			private boolean moveNext_6() throws Exception {
				state = 6;				
				if (!var4_as_object.moveNext()) {state = 7; return false; }
				current = var4_as_object.current();
				pos++;
				return true;
			}
			private boolean moveNext_7() throws Exception {
				state = 4;				
				if( var4_as_object != null ) { var4_as_object.close(); var4_as_object = null; }
				return false;
			}


			public void close() {
				try {
					if( var4_as_object != null ) { var4_as_object.close(); var4_as_object = null; }
					if( var3_array_items != null ) { var3_array_items.close(); var3_array_items = null; }
					if( var2_as_array != null ) { var2_as_array.close(); var2_as_array = null; }
				} catch (Exception e) {
				}
			}
		}
	}
	static class seq3_filter implements IEnumerable {
		com.altova.mapforce.IMFNode var1_cur;

		public seq3_filter(com.altova.mapforce.IMFNode var1_cur)	{
			this.var1_cur = var1_cur;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}

		public static class Enumerator implements IEnumerator {
			int pos = 0;
			int state = 1;
			Object current;
			seq3_filter closure;
			IEnumerator var2_object_members;

			public Enumerator(seq3_filter closure) {
				this.closure = closure;
			}

			public Object current() {return current;}

			public int position() {return pos;}

			public boolean moveNext() throws Exception {
				while (state != 0) {
					switch (state) {
						case 1: if (moveNext_1()) return true; break;
						case 2: if (moveNext_2()) return true; break;
						case 3: if (moveNext_3()) return true; break;
					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				var2_object_members = (com.altova.functions.Json.GetObjectMembers(closure.var1_cur)).enumerator();
				return false;
			}
			private boolean moveNext_2() throws Exception {
				state = 2;				
				if (!var2_object_members.moveNext()) {state = 3; return false; }
				if (!(com.altova.functions.Json.IsValueA(((com.altova.mapforce.IMFNode)(var2_object_members.current())), "file:///C:/Users/admin/Desktop/output%20files/acmejson_2.schema.json#//definitions//products/!additionalProperties/@127"))) {state = 2; return false; }
				current = var2_object_members.current();
				pos++;
				return true;
			}
			private boolean moveNext_3() throws Exception {
				state = 0;				
				if( var2_object_members != null ) { var2_object_members.close(); var2_object_members = null; }
				return false;
			}


			public void close() {
				try {
					if( var2_object_members != null ) { var2_object_members.close(); var2_object_members = null; }
				} catch (Exception e) {
				}
			}
		}
	}
	static class seq4_join implements IEnumerable {
		com.altova.mapforce.IEnumerable var1_object_member_by_name;
		com.altova.mapforce.IMFNode var2_cur;
		com.altova.mapforce.IEnumerable var3_filter;

		public seq4_join(com.altova.mapforce.IEnumerable var1_object_member_by_name, com.altova.mapforce.IMFNode var2_cur, com.altova.mapforce.IEnumerable var3_filter)	{
			this.var1_object_member_by_name = var1_object_member_by_name;
			this.var2_cur = var2_cur;
			this.var3_filter = var3_filter;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}

		public static class Enumerator implements IEnumerator {
			int pos = 0;
			int state = 1;
			Object current;
			seq4_join closure;
			IEnumerator var4_object_member_by_name;
			IEnumerator var5_as_string;
			IEnumerator var6_object_member_by_name;
			IEnumerator var7_as_string;
			IEnumerator var8_object_member_by_name;
			IEnumerator var9_as_string;
			IEnumerator var10_object_member_by_name;
			IEnumerator var11_as_string;
			IEnumerator var12_object_member_by_name;
			IEnumerator var13_as_boolean;
			IEnumerator var14_object_member_by_name;
			IEnumerator var15_as_string;
			IEnumerator var16_object_member_by_name;
			IEnumerator var17_as_string;
			IEnumerator var18_object_member_by_name;
			IEnumerator var19_as_string;
			IEnumerator var20_object_member_by_name;
			IEnumerator var21_as_string;
			IEnumerator var22_object_member_by_name;
			IEnumerator var23_as_string;

			public Enumerator(seq4_join closure) {
				this.closure = closure;
			}

			public Object current() {return current;}

			public int position() {return pos;}

			public boolean moveNext() throws Exception {
				while (state != 0) {
					switch (state) {
						case 1: if (moveNext_1()) return true; break;
						case 2: if (moveNext_2()) return true; break;
						case 3: if (moveNext_3()) return true; break;
						case 4: if (moveNext_4()) return true; break;
						case 5: if (moveNext_5()) return true; break;
						case 7: if (moveNext_7()) return true; break;
						case 8: if (moveNext_8()) return true; break;
						case 9: if (moveNext_9()) return true; break;
						case 10: if (moveNext_10()) return true; break;
						case 12: if (moveNext_12()) return true; break;
						case 13: if (moveNext_13()) return true; break;
						case 14: if (moveNext_14()) return true; break;
						case 15: if (moveNext_15()) return true; break;
						case 17: if (moveNext_17()) return true; break;
						case 18: if (moveNext_18()) return true; break;
						case 19: if (moveNext_19()) return true; break;
						case 20: if (moveNext_20()) return true; break;
						case 22: if (moveNext_22()) return true; break;
						case 23: if (moveNext_23()) return true; break;
						case 24: if (moveNext_24()) return true; break;
						case 25: if (moveNext_25()) return true; break;
						case 27: if (moveNext_27()) return true; break;
						case 28: if (moveNext_28()) return true; break;
						case 29: if (moveNext_29()) return true; break;
						case 30: if (moveNext_30()) return true; break;
						case 31: if (moveNext_31()) return true; break;
						case 33: if (moveNext_33()) return true; break;
						case 34: if (moveNext_34()) return true; break;
						case 35: if (moveNext_35()) return true; break;
						case 36: if (moveNext_36()) return true; break;
						case 38: if (moveNext_38()) return true; break;
						case 39: if (moveNext_39()) return true; break;
						case 40: if (moveNext_40()) return true; break;
						case 41: if (moveNext_41()) return true; break;
						case 43: if (moveNext_43()) return true; break;
						case 44: if (moveNext_44()) return true; break;
						case 45: if (moveNext_45()) return true; break;
						case 46: if (moveNext_46()) return true; break;
						case 48: if (moveNext_48()) return true; break;
						case 49: if (moveNext_49()) return true; break;
						case 50: if (moveNext_50()) return true; break;
						case 51: if (moveNext_51()) return true; break;
						case 53: if (moveNext_53()) return true; break;
					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				var4_object_member_by_name = (com.altova.functions.Json.GetMemberByName(closure.var2_cur, "salsify:id")).enumerator();
				return false;
			}
			private boolean moveNext_2() throws Exception {
				state = 4;				
				if (!var4_object_member_by_name.moveNext()) {state = 3; return false; }
				var5_as_string = (com.altova.functions.Json.AsString(com.altova.functions.Json.GetMemberValue(((com.altova.mapforce.IMFNode)(var4_object_member_by_name.current()))))).enumerator();
				return false;
			}
			private boolean moveNext_3() throws Exception {
				state = 7;				
				if( var4_object_member_by_name != null ) { var4_object_member_by_name.close(); var4_object_member_by_name = null; }
				var6_object_member_by_name = (com.altova.functions.Json.GetMemberByName(closure.var2_cur, "Product Name")).enumerator();
				return false;
			}
			private boolean moveNext_4() throws Exception {
				state = 4;				
				if (!var5_as_string.moveNext()) {state = 5; return false; }
				current = com.altova.functions.Core.createAttribute(com.altova.functions.Core.createQName("product-id", ""), com.altova.functions.Core.box(((java.lang.String)(var5_as_string.current()))));
				pos++;
				return true;
			}
			private boolean moveNext_5() throws Exception {
				state = 2;				
				if( var5_as_string != null ) { var5_as_string.close(); var5_as_string = null; }
				return false;
			}
			private boolean moveNext_7() throws Exception {
				state = 9;				
				if (!var6_object_member_by_name.moveNext()) {state = 8; return false; }
				var7_as_string = (com.altova.functions.Json.AsString(com.altova.functions.Json.GetMemberValue(((com.altova.mapforce.IMFNode)(var6_object_member_by_name.current()))))).enumerator();
				return false;
			}
			private boolean moveNext_8() throws Exception {
				state = 12;				
				if( var6_object_member_by_name != null ) { var6_object_member_by_name.close(); var6_object_member_by_name = null; }
				var8_object_member_by_name = (com.altova.functions.Json.GetMemberByName(closure.var2_cur, "Short Description")).enumerator();
				return false;
			}
			private boolean moveNext_9() throws Exception {
				state = 9;				
				if (!var7_as_string.moveNext()) {state = 10; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("display-name", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), com.altova.functions.Core.box(((java.lang.String)(var7_as_string.current()))));
				pos++;
				return true;
			}
			private boolean moveNext_10() throws Exception {
				state = 7;				
				if( var7_as_string != null ) { var7_as_string.close(); var7_as_string = null; }
				return false;
			}
			private boolean moveNext_12() throws Exception {
				state = 14;				
				if (!var8_object_member_by_name.moveNext()) {state = 13; return false; }
				var9_as_string = (com.altova.functions.Json.AsString(com.altova.functions.Json.GetMemberValue(((com.altova.mapforce.IMFNode)(var8_object_member_by_name.current()))))).enumerator();
				return false;
			}
			private boolean moveNext_13() throws Exception {
				state = 17;				
				if( var8_object_member_by_name != null ) { var8_object_member_by_name.close(); var8_object_member_by_name = null; }
				var10_object_member_by_name = (com.altova.functions.Json.GetMemberByName(closure.var2_cur, "Marketing Copy")).enumerator();
				return false;
			}
			private boolean moveNext_14() throws Exception {
				state = 14;				
				if (!var9_as_string.moveNext()) {state = 15; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("short-description", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), com.altova.functions.Core.box(((java.lang.String)(var9_as_string.current()))));
				pos++;
				return true;
			}
			private boolean moveNext_15() throws Exception {
				state = 12;				
				if( var9_as_string != null ) { var9_as_string.close(); var9_as_string = null; }
				return false;
			}
			private boolean moveNext_17() throws Exception {
				state = 19;				
				if (!var10_object_member_by_name.moveNext()) {state = 18; return false; }
				var11_as_string = (com.altova.functions.Json.AsString(com.altova.functions.Json.GetMemberValue(((com.altova.mapforce.IMFNode)(var10_object_member_by_name.current()))))).enumerator();
				return false;
			}
			private boolean moveNext_18() throws Exception {
				state = 22;				
				if( var10_object_member_by_name != null ) { var10_object_member_by_name.close(); var10_object_member_by_name = null; }
				var12_object_member_by_name = (com.altova.functions.Json.GetMemberByName(closure.var2_cur, "BUYABLE")).enumerator();
				return false;
			}
			private boolean moveNext_19() throws Exception {
				state = 19;				
				if (!var11_as_string.moveNext()) {state = 20; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("long-description", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), com.altova.functions.Core.box(((java.lang.String)(var11_as_string.current()))));
				pos++;
				return true;
			}
			private boolean moveNext_20() throws Exception {
				state = 17;				
				if( var11_as_string != null ) { var11_as_string.close(); var11_as_string = null; }
				return false;
			}
			private boolean moveNext_22() throws Exception {
				state = 24;				
				if (!var12_object_member_by_name.moveNext()) {state = 23; return false; }
				var13_as_boolean = (com.altova.functions.Json.AsBoolean(com.altova.functions.Json.GetMemberValue(((com.altova.mapforce.IMFNode)(var12_object_member_by_name.current()))))).enumerator();
				return false;
			}
			private boolean moveNext_23() throws Exception {
				state = 27;				
				if( var12_object_member_by_name != null ) { var12_object_member_by_name.close(); var12_object_member_by_name = null; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("images", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), (new seq5_join(closure.var1_object_member_by_name, closure.var3_filter)));
				pos++;
				return true;
			}
			private boolean moveNext_24() throws Exception {
				state = 24;				
				if (!var13_as_boolean.moveNext()) {state = 25; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("online-flag", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), com.altova.functions.Core.box(com.altova.CoreTypes.booleanToString(((Boolean)(var13_as_boolean.current())))));
				pos++;
				return true;
			}
			private boolean moveNext_25() throws Exception {
				state = 22;				
				if( var13_as_boolean != null ) { var13_as_boolean.close(); var13_as_boolean = null; }
				return false;
			}
			private boolean moveNext_27() throws Exception {
				state = 28;				
				var14_object_member_by_name = (closure.var1_object_member_by_name).enumerator();
				return false;
			}
			private boolean moveNext_28() throws Exception {
				state = 30;				
				if (!var14_object_member_by_name.moveNext()) {state = 29; return false; }
				var15_as_string = (com.altova.functions.Json.AsString(com.altova.functions.Json.GetMemberValue(((com.altova.mapforce.IMFNode)(var14_object_member_by_name.current()))))).enumerator();
				return false;
			}
			private boolean moveNext_29() throws Exception {
				state = 33;				
				if( var14_object_member_by_name != null ) { var14_object_member_by_name.close(); var14_object_member_by_name = null; }
				var16_object_member_by_name = (closure.var1_object_member_by_name).enumerator();
				return false;
			}
			private boolean moveNext_30() throws Exception {
				state = 30;				
				if (!var15_as_string.moveNext()) {state = 31; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("image", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), com.altova.functions.Core.box(((java.lang.String)(var15_as_string.current()))));
				pos++;
				return true;
			}
			private boolean moveNext_31() throws Exception {
				state = 28;				
				if( var15_as_string != null ) { var15_as_string.close(); var15_as_string = null; }
				return false;
			}
			private boolean moveNext_33() throws Exception {
				state = 35;				
				if (!var16_object_member_by_name.moveNext()) {state = 34; return false; }
				var17_as_string = (com.altova.functions.Json.AsString(com.altova.functions.Json.GetMemberValue(((com.altova.mapforce.IMFNode)(var16_object_member_by_name.current()))))).enumerator();
				return false;
			}
			private boolean moveNext_34() throws Exception {
				state = 38;				
				if( var16_object_member_by_name != null ) { var16_object_member_by_name.close(); var16_object_member_by_name = null; }
				var18_object_member_by_name = (com.altova.functions.Json.GetMemberByName(closure.var2_cur, "SEO Brand Name Display")).enumerator();
				return false;
			}
			private boolean moveNext_35() throws Exception {
				state = 35;				
				if (!var17_as_string.moveNext()) {state = 36; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("thumbnail", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), com.altova.functions.Core.box(((java.lang.String)(var17_as_string.current()))));
				pos++;
				return true;
			}
			private boolean moveNext_36() throws Exception {
				state = 33;				
				if( var17_as_string != null ) { var17_as_string.close(); var17_as_string = null; }
				return false;
			}
			private boolean moveNext_38() throws Exception {
				state = 40;				
				if (!var18_object_member_by_name.moveNext()) {state = 39; return false; }
				var19_as_string = (com.altova.functions.Json.AsString(com.altova.functions.Json.GetMemberValue(((com.altova.mapforce.IMFNode)(var18_object_member_by_name.current()))))).enumerator();
				return false;
			}
			private boolean moveNext_39() throws Exception {
				state = 43;				
				if( var18_object_member_by_name != null ) { var18_object_member_by_name.close(); var18_object_member_by_name = null; }
				var20_object_member_by_name = (com.altova.functions.Json.GetMemberByName(closure.var2_cur, "MFG Name")).enumerator();
				return false;
			}
			private boolean moveNext_40() throws Exception {
				state = 40;				
				if (!var19_as_string.moveNext()) {state = 41; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("brand", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), com.altova.functions.Core.box(((java.lang.String)(var19_as_string.current()))));
				pos++;
				return true;
			}
			private boolean moveNext_41() throws Exception {
				state = 38;				
				if( var19_as_string != null ) { var19_as_string.close(); var19_as_string = null; }
				return false;
			}
			private boolean moveNext_43() throws Exception {
				state = 45;				
				if (!var20_object_member_by_name.moveNext()) {state = 44; return false; }
				var21_as_string = (com.altova.functions.Json.AsString(com.altova.functions.Json.GetMemberValue(((com.altova.mapforce.IMFNode)(var20_object_member_by_name.current()))))).enumerator();
				return false;
			}
			private boolean moveNext_44() throws Exception {
				state = 48;				
				if( var20_object_member_by_name != null ) { var20_object_member_by_name.close(); var20_object_member_by_name = null; }
				var22_object_member_by_name = (com.altova.functions.Json.GetMemberByName(closure.var2_cur, "MFG Part # (OEM)")).enumerator();
				return false;
			}
			private boolean moveNext_45() throws Exception {
				state = 45;				
				if (!var21_as_string.moveNext()) {state = 46; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("manufacturer-name", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), com.altova.functions.Core.box(((java.lang.String)(var21_as_string.current()))));
				pos++;
				return true;
			}
			private boolean moveNext_46() throws Exception {
				state = 43;				
				if( var21_as_string != null ) { var21_as_string.close(); var21_as_string = null; }
				return false;
			}
			private boolean moveNext_48() throws Exception {
				state = 50;				
				if (!var22_object_member_by_name.moveNext()) {state = 49; return false; }
				var23_as_string = (com.altova.functions.Json.AsString(com.altova.functions.Json.GetMemberValue(((com.altova.mapforce.IMFNode)(var22_object_member_by_name.current()))))).enumerator();
				return false;
			}
			private boolean moveNext_49() throws Exception {
				state = 53;				
				if( var22_object_member_by_name != null ) { var22_object_member_by_name.close(); var22_object_member_by_name = null; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("page-attributes", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), (new seq10_join(closure.var2_cur)));
				pos++;
				return true;
			}
			private boolean moveNext_50() throws Exception {
				state = 50;				
				if (!var23_as_string.moveNext()) {state = 51; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("manufacturer-sku", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), com.altova.functions.Core.box(((java.lang.String)(var23_as_string.current()))));
				pos++;
				return true;
			}
			private boolean moveNext_51() throws Exception {
				state = 48;				
				if( var23_as_string != null ) { var23_as_string.close(); var23_as_string = null; }
				return false;
			}
			private boolean moveNext_53() throws Exception {
				state = 0;				
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("custom-attributes", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), (new seq11_map(closure.var3_filter)));
				pos++;
				return true;
			}


			public void close() {
				try {
					if( var5_as_string != null ) { var5_as_string.close(); var5_as_string = null; }
					if( var4_object_member_by_name != null ) { var4_object_member_by_name.close(); var4_object_member_by_name = null; }
					if( var7_as_string != null ) { var7_as_string.close(); var7_as_string = null; }
					if( var6_object_member_by_name != null ) { var6_object_member_by_name.close(); var6_object_member_by_name = null; }
					if( var9_as_string != null ) { var9_as_string.close(); var9_as_string = null; }
					if( var8_object_member_by_name != null ) { var8_object_member_by_name.close(); var8_object_member_by_name = null; }
					if( var11_as_string != null ) { var11_as_string.close(); var11_as_string = null; }
					if( var10_object_member_by_name != null ) { var10_object_member_by_name.close(); var10_object_member_by_name = null; }
					if( var13_as_boolean != null ) { var13_as_boolean.close(); var13_as_boolean = null; }
					if( var12_object_member_by_name != null ) { var12_object_member_by_name.close(); var12_object_member_by_name = null; }
					if( var15_as_string != null ) { var15_as_string.close(); var15_as_string = null; }
					if( var14_object_member_by_name != null ) { var14_object_member_by_name.close(); var14_object_member_by_name = null; }
					if( var17_as_string != null ) { var17_as_string.close(); var17_as_string = null; }
					if( var16_object_member_by_name != null ) { var16_object_member_by_name.close(); var16_object_member_by_name = null; }
					if( var19_as_string != null ) { var19_as_string.close(); var19_as_string = null; }
					if( var18_object_member_by_name != null ) { var18_object_member_by_name.close(); var18_object_member_by_name = null; }
					if( var21_as_string != null ) { var21_as_string.close(); var21_as_string = null; }
					if( var20_object_member_by_name != null ) { var20_object_member_by_name.close(); var20_object_member_by_name = null; }
					if( var23_as_string != null ) { var23_as_string.close(); var23_as_string = null; }
					if( var22_object_member_by_name != null ) { var22_object_member_by_name.close(); var22_object_member_by_name = null; }
				} catch (Exception e) {
				}
			}
		}
	}
	static class seq5_join implements IEnumerable {
		com.altova.mapforce.IEnumerable var1_object_member_by_name;
		com.altova.mapforce.IEnumerable var2_filter;

		public seq5_join(com.altova.mapforce.IEnumerable var1_object_member_by_name, com.altova.mapforce.IEnumerable var2_filter)	{
			this.var1_object_member_by_name = var1_object_member_by_name;
			this.var2_filter = var2_filter;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}

		public static class Enumerator implements IEnumerator {
			int pos = 0;
			int state = 1;
			Object current;
			seq5_join closure;
			IEnumerator var3_subcategories;

			public Enumerator(seq5_join closure) {
				this.closure = closure;
			}

			public Object current() {return current;}

			public int position() {return pos;}

			public boolean moveNext() throws Exception {
				while (state != 0) {
					switch (state) {
						case 1: if (moveNext_1()) return true; break;
						case 2: if (moveNext_2()) return true; break;
						case 3: if (moveNext_3()) return true; break;
					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				var3_subcategories = (com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("subcategories", ""), com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("root", ""), (new seq6_map(closure.var2_filter))))).enumerator();
				return false;
			}
			private boolean moveNext_2() throws Exception {
				state = 2;				
				if (!var3_subcategories.moveNext()) {state = 3; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("image-group", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), com.altova.functions.Core.box(com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("image", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), (new seq8_map(((com.altova.mapforce.IMFNode)(var3_subcategories.current())))))));
				pos++;
				return true;
			}
			private boolean moveNext_3() throws Exception {
				state = 0;				
				if( var3_subcategories != null ) { var3_subcategories.close(); var3_subcategories = null; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("image-group", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), com.altova.functions.Core.box(com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("image", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), (new seq9_join(closure.var1_object_member_by_name)))));
				pos++;
				return true;
			}


			public void close() {
				try {
					if( var3_subcategories != null ) { var3_subcategories.close(); var3_subcategories = null; }
				} catch (Exception e) {
				}
			}
		}
	}
	static class seq6_map implements IEnumerable {
		com.altova.mapforce.IEnumerable var1_filter;

		public seq6_map(com.altova.mapforce.IEnumerable var1_filter)	{
			this.var1_filter = var1_filter;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}

		public static class Enumerator implements IEnumerator {
			int pos = 0;
			int state = 1;
			Object current;
			seq6_map closure;
			IEnumerator var2_filter;

			public Enumerator(seq6_map closure) {
				this.closure = closure;
			}

			public Object current() {return current;}

			public int position() {return pos;}

			public boolean moveNext() throws Exception {
				while (state != 0) {
					switch (state) {
						case 1: if (moveNext_1()) return true; break;
						case 2: if (moveNext_2()) return true; break;
						case 3: if (moveNext_3()) return true; break;
					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				var2_filter = (closure.var1_filter).enumerator();
				return false;
			}
			private boolean moveNext_2() throws Exception {
				state = 2;				
				if (!var2_filter.moveNext()) {state = 3; return false; }
				if (!(com.altova.functions.Core.startsWith(com.altova.functions.Json.GetMemberName(((com.altova.mapforce.IMFNode)(var2_filter.current()))), "Detailed Product View"))) {state = 2; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("subcategories", ""), (new seq7_join(((com.altova.mapforce.IMFNode)(var2_filter.current())))));
				pos++;
				return true;
			}
			private boolean moveNext_3() throws Exception {
				state = 0;				
				if( var2_filter != null ) { var2_filter.close(); var2_filter = null; }
				return false;
			}


			public void close() {
				try {
					if( var2_filter != null ) { var2_filter.close(); var2_filter = null; }
				} catch (Exception e) {
				}
			}
		}
	}
	static class seq7_join implements IEnumerable {
		com.altova.mapforce.IMFNode var1_current;

		public seq7_join(com.altova.mapforce.IMFNode var1_current)	{
			this.var1_current = var1_current;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}

		public static class Enumerator implements IEnumerator {
			int pos = 0;
			int state = 1;
			Object current;
			seq7_join closure;
			IEnumerator var2_as_string;

			public Enumerator(seq7_join closure) {
				this.closure = closure;
			}

			public Object current() {return current;}

			public int position() {return pos;}

			public boolean moveNext() throws Exception {
				while (state != 0) {
					switch (state) {
						case 1: if (moveNext_1()) return true; break;
						case 2: if (moveNext_2()) return true; break;
						case 3: if (moveNext_3()) return true; break;
						case 4: if (moveNext_4()) return true; break;
					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("name", ""), com.altova.functions.Core.box(com.altova.functions.Json.GetMemberName(closure.var1_current)));
				pos++;
				return true;
			}
			private boolean moveNext_2() throws Exception {
				state = 3;				
				var2_as_string = (com.altova.functions.Json.AsString(com.altova.functions.Json.GetMemberValue(closure.var1_current))).enumerator();
				return false;
			}
			private boolean moveNext_3() throws Exception {
				state = 3;				
				if (!var2_as_string.moveNext()) {state = 4; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("value", ""), com.altova.functions.Core.box(((java.lang.String)(var2_as_string.current()))));
				pos++;
				return true;
			}
			private boolean moveNext_4() throws Exception {
				state = 0;				
				if( var2_as_string != null ) { var2_as_string.close(); var2_as_string = null; }
				return false;
			}


			public void close() {
				try {
					if( var2_as_string != null ) { var2_as_string.close(); var2_as_string = null; }
				} catch (Exception e) {
				}
			}
		}
	}
	static class seq8_map implements IEnumerable {
		com.altova.mapforce.IMFNode var1_cur;

		public seq8_map(com.altova.mapforce.IMFNode var1_cur)	{
			this.var1_cur = var1_cur;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}

		public static class Enumerator implements IEnumerator {
			int pos = 0;
			int state = 1;
			Object current;
			seq8_map closure;
			IEnumerator var2_value;

			public Enumerator(seq8_map closure) {
				this.closure = closure;
			}

			public Object current() {return current;}

			public int position() {return pos;}

			public boolean moveNext() throws Exception {
				while (state != 0) {
					switch (state) {
						case 1: if (moveNext_1()) return true; break;
						case 2: if (moveNext_2()) return true; break;
						case 3: if (moveNext_3()) return true; break;
					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				var2_value = (com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("value", ""), closure.var1_cur)).enumerator();
				return false;
			}
			private boolean moveNext_2() throws Exception {
				state = 2;				
				if (!var2_value.moveNext()) {state = 3; return false; }
				current = com.altova.functions.Core.createAttribute(com.altova.functions.Core.createQName("path", ""), com.altova.functions.Core.box(com.altova.CoreTypes.nodeToString(((com.altova.mapforce.IMFNode)(var2_value.current())))));
				pos++;
				return true;
			}
			private boolean moveNext_3() throws Exception {
				state = 0;				
				if( var2_value != null ) { var2_value.close(); var2_value = null; }
				return false;
			}


			public void close() {
				try {
					if( var2_value != null ) { var2_value.close(); var2_value = null; }
				} catch (Exception e) {
				}
			}
		}
	}
	static class seq9_join implements IEnumerable {
		com.altova.mapforce.IEnumerable var1_object_member_by_name;

		public seq9_join(com.altova.mapforce.IEnumerable var1_object_member_by_name)	{
			this.var1_object_member_by_name = var1_object_member_by_name;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}

		public static class Enumerator implements IEnumerator {
			int pos = 0;
			int state = 1;
			Object current;
			seq9_join closure;
			IEnumerator var2_object_member_by_name;
			IEnumerator var3_as_string;

			public Enumerator(seq9_join closure) {
				this.closure = closure;
			}

			public Object current() {return current;}

			public int position() {return pos;}

			public boolean moveNext() throws Exception {
				while (state != 0) {
					switch (state) {
						case 1: if (moveNext_1()) return true; break;
						case 2: if (moveNext_2()) return true; break;
						case 3: if (moveNext_3()) return true; break;
						case 4: if (moveNext_4()) return true; break;
						case 5: if (moveNext_5()) return true; break;
					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				var2_object_member_by_name = (closure.var1_object_member_by_name).enumerator();
				return false;
			}
			private boolean moveNext_2() throws Exception {
				state = 4;				
				if (!var2_object_member_by_name.moveNext()) {state = 3; return false; }
				var3_as_string = (com.altova.functions.Json.AsString(com.altova.functions.Json.GetMemberValue(((com.altova.mapforce.IMFNode)(var2_object_member_by_name.current()))))).enumerator();
				return false;
			}
			private boolean moveNext_3() throws Exception {
				state = 0;				
				if( var2_object_member_by_name != null ) { var2_object_member_by_name.close(); var2_object_member_by_name = null; }
				return false;
			}
			private boolean moveNext_4() throws Exception {
				state = 4;				
				if (!var3_as_string.moveNext()) {state = 5; return false; }
				current = com.altova.functions.Core.createAttribute(com.altova.functions.Core.createQName("path", ""), com.altova.functions.Core.box(((java.lang.String)(var3_as_string.current()))));
				pos++;
				return true;
			}
			private boolean moveNext_5() throws Exception {
				state = 2;				
				if( var3_as_string != null ) { var3_as_string.close(); var3_as_string = null; }
				return false;
			}


			public void close() {
				try {
					if( var3_as_string != null ) { var3_as_string.close(); var3_as_string = null; }
					if( var2_object_member_by_name != null ) { var2_object_member_by_name.close(); var2_object_member_by_name = null; }
				} catch (Exception e) {
				}
			}
		}
	}
	static class seq10_join implements IEnumerable {
		com.altova.mapforce.IMFNode var1_cur;

		public seq10_join(com.altova.mapforce.IMFNode var1_cur)	{
			this.var1_cur = var1_cur;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}

		public static class Enumerator implements IEnumerator {
			int pos = 0;
			int state = 1;
			Object current;
			seq10_join closure;
			IEnumerator var2_object_member_by_name;
			IEnumerator var3_as_string;
			IEnumerator var4_object_member_by_name;
			IEnumerator var5_as_string;

			public Enumerator(seq10_join closure) {
				this.closure = closure;
			}

			public Object current() {return current;}

			public int position() {return pos;}

			public boolean moveNext() throws Exception {
				while (state != 0) {
					switch (state) {
						case 1: if (moveNext_1()) return true; break;
						case 2: if (moveNext_2()) return true; break;
						case 3: if (moveNext_3()) return true; break;
						case 4: if (moveNext_4()) return true; break;
						case 5: if (moveNext_5()) return true; break;
						case 7: if (moveNext_7()) return true; break;
						case 8: if (moveNext_8()) return true; break;
						case 9: if (moveNext_9()) return true; break;
						case 10: if (moveNext_10()) return true; break;
					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				var2_object_member_by_name = (com.altova.functions.Json.GetMemberByName(closure.var1_cur, "Search Keywords")).enumerator();
				return false;
			}
			private boolean moveNext_2() throws Exception {
				state = 4;				
				if (!var2_object_member_by_name.moveNext()) {state = 3; return false; }
				var3_as_string = (com.altova.functions.Json.AsString(com.altova.functions.Json.GetMemberValue(((com.altova.mapforce.IMFNode)(var2_object_member_by_name.current()))))).enumerator();
				return false;
			}
			private boolean moveNext_3() throws Exception {
				state = 7;				
				if( var2_object_member_by_name != null ) { var2_object_member_by_name.close(); var2_object_member_by_name = null; }
				var4_object_member_by_name = (com.altova.functions.Json.GetMemberByName(closure.var1_cur, "SEO URL Keywword")).enumerator();
				return false;
			}
			private boolean moveNext_4() throws Exception {
				state = 4;				
				if (!var3_as_string.moveNext()) {state = 5; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("page-keywords", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), com.altova.functions.Core.box(((java.lang.String)(var3_as_string.current()))));
				pos++;
				return true;
			}
			private boolean moveNext_5() throws Exception {
				state = 2;				
				if( var3_as_string != null ) { var3_as_string.close(); var3_as_string = null; }
				return false;
			}
			private boolean moveNext_7() throws Exception {
				state = 9;				
				if (!var4_object_member_by_name.moveNext()) {state = 8; return false; }
				var5_as_string = (com.altova.functions.Json.AsString(com.altova.functions.Json.GetMemberValue(((com.altova.mapforce.IMFNode)(var4_object_member_by_name.current()))))).enumerator();
				return false;
			}
			private boolean moveNext_8() throws Exception {
				state = 0;				
				if( var4_object_member_by_name != null ) { var4_object_member_by_name.close(); var4_object_member_by_name = null; }
				return false;
			}
			private boolean moveNext_9() throws Exception {
				state = 9;				
				if (!var5_as_string.moveNext()) {state = 10; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("page-url", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), com.altova.functions.Core.box(((java.lang.String)(var5_as_string.current()))));
				pos++;
				return true;
			}
			private boolean moveNext_10() throws Exception {
				state = 7;				
				if( var5_as_string != null ) { var5_as_string.close(); var5_as_string = null; }
				return false;
			}


			public void close() {
				try {
					if( var3_as_string != null ) { var3_as_string.close(); var3_as_string = null; }
					if( var2_object_member_by_name != null ) { var2_object_member_by_name.close(); var2_object_member_by_name = null; }
					if( var5_as_string != null ) { var5_as_string.close(); var5_as_string = null; }
					if( var4_object_member_by_name != null ) { var4_object_member_by_name.close(); var4_object_member_by_name = null; }
				} catch (Exception e) {
				}
			}
		}
	}
	static class seq11_map implements IEnumerable {
		com.altova.mapforce.IEnumerable var1_filter;

		public seq11_map(com.altova.mapforce.IEnumerable var1_filter)	{
			this.var1_filter = var1_filter;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}

		public static class Enumerator implements IEnumerator {
			int pos = 0;
			int state = 1;
			Object current;
			seq11_map closure;
			IEnumerator var2_subcategories;

			public Enumerator(seq11_map closure) {
				this.closure = closure;
			}

			public Object current() {return current;}

			public int position() {return pos;}

			public boolean moveNext() throws Exception {
				while (state != 0) {
					switch (state) {
						case 1: if (moveNext_1()) return true; break;
						case 2: if (moveNext_2()) return true; break;
						case 3: if (moveNext_3()) return true; break;
					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				var2_subcategories = (com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("subcategories", ""), com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("root", ""), (new seq12_map(closure.var1_filter))))).enumerator();
				return false;
			}
			private boolean moveNext_2() throws Exception {
				state = 2;				
				if (!var2_subcategories.moveNext()) {state = 3; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("custom-attribute", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), (new seq13_join(((com.altova.mapforce.IMFNode)(var2_subcategories.current())))));
				pos++;
				return true;
			}
			private boolean moveNext_3() throws Exception {
				state = 0;				
				if( var2_subcategories != null ) { var2_subcategories.close(); var2_subcategories = null; }
				return false;
			}


			public void close() {
				try {
					if( var2_subcategories != null ) { var2_subcategories.close(); var2_subcategories = null; }
				} catch (Exception e) {
				}
			}
		}
	}
	static class seq12_map implements IEnumerable {
		com.altova.mapforce.IEnumerable var1_filter;

		public seq12_map(com.altova.mapforce.IEnumerable var1_filter)	{
			this.var1_filter = var1_filter;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}

		public static class Enumerator implements IEnumerator {
			int pos = 0;
			int state = 1;
			Object current;
			seq12_map closure;
			IEnumerator var2_filter;
			java.lang.String var3_member_name;

			public Enumerator(seq12_map closure) {
				this.closure = closure;
			}

			public Object current() {return current;}

			public int position() {return pos;}

			public boolean moveNext() throws Exception {
				while (state != 0) {
					switch (state) {
						case 1: if (moveNext_1()) return true; break;
						case 2: if (moveNext_2()) return true; break;
						case 3: if (moveNext_3()) return true; break;
					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				var2_filter = (closure.var1_filter).enumerator();
				return false;
			}
			private boolean moveNext_2() throws Exception {
				state = 2;				
				if (!var2_filter.moveNext()) {state = 3; return false; }
				var3_member_name = com.altova.functions.Json.GetMemberName(((com.altova.mapforce.IMFNode)(var2_filter.current())));
				if (!(com.altova.functions.Core.logicalNot(com.altova.functions.Core.logicalAnd(com.altova.functions.Core.startsWith(var3_member_name, "Detailed Product View"), com.altova.functions.Core.logicalNot(com.altova.functions.Core.startsWith(var3_member_name, "Acme Tools Salesforce")))))) {state = 2; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("subcategories", ""), (new seq7_join(((com.altova.mapforce.IMFNode)(var2_filter.current())))));
				pos++;
				return true;
			}
			private boolean moveNext_3() throws Exception {
				state = 0;				
				if( var2_filter != null ) { var2_filter.close(); var2_filter = null; }
				return false;
			}


			public void close() {
				try {
					if( var2_filter != null ) { var2_filter.close(); var2_filter = null; }
				} catch (Exception e) {
				}
			}
		}
	}
	static class seq13_join implements IEnumerable {
		com.altova.mapforce.IMFNode var1_cur;

		public seq13_join(com.altova.mapforce.IMFNode var1_cur)	{
			this.var1_cur = var1_cur;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}

		public static class Enumerator implements IEnumerator {
			int pos = 0;
			int state = 1;
			Object current;
			seq13_join closure;
			IEnumerator var2_name;
			IEnumerator var3_value;

			public Enumerator(seq13_join closure) {
				this.closure = closure;
			}

			public Object current() {return current;}

			public int position() {return pos;}

			public boolean moveNext() throws Exception {
				while (state != 0) {
					switch (state) {
						case 1: if (moveNext_1()) return true; break;
						case 2: if (moveNext_2()) return true; break;
						case 3: if (moveNext_3()) return true; break;
						case 5: if (moveNext_5()) return true; break;
						case 6: if (moveNext_6()) return true; break;
					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				var2_name = (com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("name", ""), closure.var1_cur)).enumerator();
				return false;
			}
			private boolean moveNext_2() throws Exception {
				state = 2;				
				if (!var2_name.moveNext()) {state = 3; return false; }
				current = com.altova.functions.Core.createAttribute(com.altova.functions.Core.createQName("attribute-id", ""), com.altova.functions.Core.box(com.altova.CoreTypes.nodeToString(((com.altova.mapforce.IMFNode)(var2_name.current())))));
				pos++;
				return true;
			}
			private boolean moveNext_3() throws Exception {
				state = 5;				
				if( var2_name != null ) { var2_name.close(); var2_name = null; }
				var3_value = (com.altova.functions.Core.filterElements(com.altova.functions.Core.createQName("value", ""), closure.var1_cur)).enumerator();
				return false;
			}
			private boolean moveNext_5() throws Exception {
				state = 5;				
				if (!var3_value.moveNext()) {state = 6; return false; }
				current = com.altova.functions.Core.createElement(com.altova.functions.Core.createQName("value", "http://www.demandware.com/xml/impex/catalog/2006-10-31"), com.altova.functions.Core.box(com.altova.CoreTypes.nodeToString(((com.altova.mapforce.IMFNode)(var3_value.current())))));
				pos++;
				return true;
			}
			private boolean moveNext_6() throws Exception {
				state = 0;				
				if( var3_value != null ) { var3_value.close(); var3_value = null; }
				return false;
			}


			public void close() {
				try {
					if( var2_name != null ) { var2_name.close(); var2_name = null; }
					if( var3_value != null ) { var3_value.close(); var3_value = null; }
				} catch (Exception e) {
				}
			}
		}
	}
	static class Outer implements IEnumerable {
		com.altova.mapforce.IMFNode var1_acmejson_2_Instance;

		public Outer(com.altova.mapforce.IMFNode var1_acmejson_2_Instance)	{
			this.var1_acmejson_2_Instance = var1_acmejson_2_Instance;
		}

		public IEnumerator enumerator() {return new Enumerator(this);}

		public static class Enumerator implements IEnumerator {
			int pos = 0;
			int state = 1;
			Object current;
			Outer closure;
			IEnumerator var2_box;

			public Enumerator(Outer closure) {
				this.closure = closure;
			}

			public Object current() {return current;}

			public int position() {return pos;}

			public boolean moveNext() throws Exception {
				while (state != 0) {
					switch (state) {
						case 1: if (moveNext_1()) return true; break;
						case 2: if (moveNext_2()) return true; break;
						case 3: if (moveNext_3()) return true; break;
					}
				}
				return false;
			}

			private boolean moveNext_1() throws Exception {
				state = 2;				
				var2_box = ((new main(closure.var1_acmejson_2_Instance))).enumerator();
				return false;
			}
			private boolean moveNext_2() throws Exception {
				state = 2;				
				if (!var2_box.moveNext()) {state = 3; return false; }
				current = var2_box.current();
				pos++;
				return true;
			}
			private boolean moveNext_3() throws Exception {
				state = 0;				
				if( var2_box != null ) { var2_box.close(); var2_box = null; }
				return false;
			}


			public void close() {
				try {
					if( var2_box != null ) { var2_box.close(); var2_box = null; }
				} catch (Exception e) {
				}
			}
		}
	}


	// instances
	protected com.altova.json.Document varacmejson_23Instance;

	public void run(String acmejson_23SourceFilename, String catalog5TargetFilename) throws Exception {
		try(
			// open source streams
			com.altova.io.FileInput acmejson_23Source = new com.altova.io.FileInput(acmejson_23SourceFilename);
		// open target stream
			com.altova.io.FileOutput catalog5Target = new com.altova.io.FileOutput(catalog5TargetFilename);

		) {
			// run
			run(acmejson_23Source, catalog5Target);

		}
	}


	// main entry point

	public void run(com.altova.io.Input acmejson_23Source, com.altova.io.Output catalog5Target) throws Exception {
		// Open the source(s)
			varacmejson_23Instance = com.altova.functions.Json.Load(acmejson_23Source, MapForceJsonLibs_acmejson_2.Schemas, false, false);

		// Create the target
		org.w3c.dom.Document catalog5Doc = (catalog5Target.getType() == com.altova.io.Output.IO_DOM) ? catalog5Target.getDocument() : XmlTreeOperations.createDocument();

		// Execute mapping

		main mapping = new main(varacmejson_23Instance);

		com.altova.xml.MFDOMWriter.write(mapping, catalog5Doc);
		// Close the target
		XmlTreeOperations.saveDocument(catalog5Doc, catalog5Target, "UTF-8", false, false, true, false);


		if (runDoesCloseAll) {
			catalog5Target.close();
		}
	}



}
