////////////////////////////////////////////////////////////////////////
//
// AlsoAcceptor.java
//
// This file was generated by MapForce MapForce 2021r2sp1.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package com.altova.json;

	
public final class AlsoAcceptor {
	private Integer _minAccepting;
	private Integer _maxAccepting;
	private Reference[] _acceptors;

	public Integer getMinAccepting() { return _minAccepting; }
	public Integer getMaxAccepting() { return _maxAccepting; }
	public Reference[] getAcceptors() { return _acceptors; }

	public AlsoAcceptor(Integer minAccepting, Integer maxAccepting, Reference[] acceptors) {
		_minAccepting = minAccepting;
		_maxAccepting = maxAccepting;
		_acceptors = acceptors;
	}
}
