////////////////////////////////////////////////////////////////////////
//
// ArrayAcceptor.java
//
// This file was generated by MapForce MapForce 2021r2sp1.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package com.altova.json;

public final class ArrayAcceptor {
	private Integer _minItems;
	private Integer _maxItems;
	private boolean _uniqueItems;
	private Reference[] _items;

	public Integer getMinItems() { return _minItems; }
	public Integer getMaxItems() { return _maxItems; }
	public boolean getUniqueItems() { return _uniqueItems; }
	public Reference[] getItems() { return _items; }

	public ArrayAcceptor(Integer minItems, Integer maxItems, boolean uniqueItems, Reference[] items) {
		_minItems = minItems;
		_maxItems = maxItems;
		_uniqueItems = uniqueItems;
		_items = items;
	}
}
