////////////////////////////////////////////////////////////////////////
//
// BooleanAcceptor.java
//
// This file was generated by MapForce MapForce 2021r2sp1.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package com.altova.json;

public final class BooleanAcceptor {
	private boolean _allowFalse, _allowTrue;

	public boolean getAllowFalse() { return _allowFalse; }
	public boolean getAllowTrue() { return _allowTrue; }
	public BooleanAcceptor(boolean allowFalse, boolean allowTrue) { _allowFalse = allowFalse; _allowTrue = allowTrue; }
}
