////////////////////////////////////////////////////////////////////////
//
// Member.java
//
// This file was generated by MapForce MapForce 2021r2sp1.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package com.altova.json;

import com.altova.mapforce.IEnumerable;


public class Member implements com.altova.mapforce.IMFNode {
	String name;
	Value value;

	public Member(String name, Value value) {
		this.name = name;
		this.value = value;
	}

	public Value getValue() { return value; }
	public String getName() { return name; }

	public String getLocalName() {
		assert false : "Method is not implemented.";
		return "";
	}

	public String getNamespaceURI() {
		assert false : "Method is not implemented.";
		return "";
	}

	public int /*Altova.Mapforce.MFNodeKind*/ getNodeKind() {
		assert false : "Method is not implemented.";
		return -1;
	}

	public String getNodeName() {
		return name;
	}

	public javax.xml.namespace.QName getQName() {
		assert false : "Method is not implemented.";
		return null;
	}

	public String getPrefix() {
		assert false : "Method is not implemented.";
		return "";
	}

	public String value() throws Exception {
		throw new UnsupportedOperationException("Method is not implemented.");
	}

	public java.lang.Object typedValue() throws Exception {
		throw new UnsupportedOperationException("Method is not implemented.");
	}

	public javax.xml.namespace.QName qnameValue() {
		assert false : "Method is not implemented.";
		return null;
	}

	public IEnumerable select(int mfQueryKind, java.lang.Object query) {
		assert false : "Method is not implemented.";
		return null;
	}
}
