////////////////////////////////////////////////////////////////////////
//
// NumberAcceptor.java
//
// This file was generated by MapForce MapForce 2021r2sp1.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package com.altova.json;

public final class NumberAcceptor {
	static public class Bound {
		public final String Value;
		public final boolean Exclusive;
		public Bound(String value, boolean exclusive) { Value = value; Exclusive = exclusive; }
	}

	private Bound _minimum;
	private Bound _maximum;
	private String _multipleOf;
	private String _pattern;
	private String[] _enum;

	public Bound getMinimum() { return _minimum; }
	public Bound getMaximum() { return _maximum; }
	public String getMultipleOf() { return _multipleOf; }
	public String getPattern() { return _pattern; }
	public String[] getEnum() { return _enum; }

	public NumberAcceptor(Bound minimum, Bound maximum, String multipleOf, String pattern, String[] enum_) {
		_minimum = minimum;
		_maximum = maximum;
		_multipleOf = multipleOf;
		_pattern = pattern;
		_enum = enum_;
	}
}
