////////////////////////////////////////////////////////////////////////
//
// ObjectAcceptor.java
//
// This file was generated by MapForce MapForce 2021r2sp1.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package com.altova.json;

public final class ObjectAcceptor {
	private Integer _minProperties;
	private Integer _maxProperties;
	private PropertyGroup[] _groups;

	public Integer getMinProperties() { return _minProperties; }
	public Integer getMaxProperties() { return _maxProperties; }
	public PropertyGroup[] getGroups() { return _groups; }

	public ObjectAcceptor(Integer minProperties, Integer maxProperties, PropertyGroup[] groups) {
		_minProperties = minProperties;
		_maxProperties = maxProperties;
		_groups = groups;
	}
}
