////////////////////////////////////////////////////////////////////////
//
// PropertyGroup.java
//
// This file was generated by MapForce MapForce 2021r2sp1.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package com.altova.json;


public final class PropertyGroup {
	public enum PropertyGroupBehavior { Succeed, Fail, ContinueWithNext }

	private PropertyGroupBehavior _matchSuccess;
	private PropertyGroupBehavior _matchFailure;
	private PropertyGroupBehavior _nonMatch;
	private PropertyRule[] _rules;

	public PropertyGroupBehavior getMatchSuccess() { return _matchSuccess; }
	public PropertyGroupBehavior getMatchFailure() { return _matchFailure; }
	public PropertyGroupBehavior getNonMatch() { return _nonMatch; }
	public PropertyRule[] getRules() { return _rules; }

	public PropertyGroup(PropertyGroupBehavior matchSuccess, PropertyGroupBehavior matchFailure, PropertyGroupBehavior nonMatch, PropertyRule[] rules) {
		_matchSuccess = matchSuccess;
		_matchFailure = matchFailure;
		_nonMatch = nonMatch;
		_rules = rules;
	}
}
