////////////////////////////////////////////////////////////////////////
//
// Reference.java
//
// This file was generated by MapForce MapForce 2021r2sp1.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package com.altova.json;

public final class Reference {
	private String _reference = null;

	public String getTarget() { return _reference; }

	public Reference(String reference) {
		_reference = reference;
	}
}
