////////////////////////////////////////////////////////////////////////
//
// StringAcceptor.java
//
// This file was generated by MapForce MapForce 2021r2sp1.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package com.altova.json;

public final class StringAcceptor {
	private Integer _minLength;
	private Integer _maxLength;
	private String _pattern;
	private String[] _enum;

	public Integer getMinLength() { return _minLength; }
	public Integer getMaxLength() { return _maxLength; }
	public String getPattern() { return _pattern; }
	public String[] getEnum() { return _enum; }

	public StringAcceptor(Integer minLength, Integer maxLength, String pattern, String[] enum_) {
		_minLength = minLength;
		_maxLength = maxLength;
		_pattern = pattern;
		_enum = enum_;
	}
}
