////////////////////////////////////////////////////////////////////////
//
// Validator.java
//
// This file was generated by MapForce MapForce 2021r2sp1.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package com.altova.json;

import java.util.HashMap;

public class Validator {
	HashMap<String, ValueAcceptor> _schemamap = new HashMap<String, ValueAcceptor>();

	Validator(ValueAcceptor[] acceptors) {
		for (ValueAcceptor acceptor: acceptors) {
			_schemamap.put(acceptor.getId(), acceptor);
		}
	}
}
