////////////////////////////////////////////////////////////////////////
//
// ValueAcceptor.java
//
// This file was generated by MapForce MapForce 2021r2sp1.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the MapForce Documentation for further details.
// http://www.altova.com/mapforce
//
////////////////////////////////////////////////////////////////////////

package com.altova.json;

public final class ValueAcceptor {
	private String _id;
	private StringAcceptor _string;
	private NumberAcceptor _number;
	private BooleanAcceptor _boolean;
	private NullAcceptor _null;
	private ArrayAcceptor _array;
	private ObjectAcceptor _object;
	private AlsoAcceptor[] _also;

	public String getId() { return _id; }
	public StringAcceptor getString() { return _string; }
	public NumberAcceptor getNumber() { return _number; }
	public BooleanAcceptor getBoolean() { return _boolean; }
	public NullAcceptor getNull() { return _null; }
	public ArrayAcceptor getArray() { return _array; }
	public ObjectAcceptor getObject() { return _object; }
	public AlsoAcceptor[] getAlso() { return _also; }

	public ValueAcceptor(String id, StringAcceptor string_, NumberAcceptor number, BooleanAcceptor boolean_, NullAcceptor null_, ArrayAcceptor array, ObjectAcceptor object_, AlsoAcceptor[] also) {
		_id = id;
		_string = string_;
		_number = number;
		_boolean = boolean_;
		_null = null_;
		_array = array;
		_object = object_;
		_also = also;
	}
}
